---
- name: Install Jenkins CI/CD
  hosts: centos_remote_a
  tasks:
    - name: Docker test exists
      shell: docker ps --all --quiet --filter=name="conferenceapp"
      register: conference_id
    - name: Delete container if exist
      shell: docker rm -f conferenceapp
      when: conference_id.stdout != ""
    - name: Start test container
      shell: docker run -d --name conference-test -p 10100:8080 adimurro/conference-application